apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myd
  name: myd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myd
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: myd
    spec:
      containers:
      - image: rishabh76/my_riddle_flaskapp:v1
        name: my-riddle-flaskapp-67k22
        command: ["python3", "/app.py"]
      restartPolicy: Always
