apiVersion: v1
kind: Service
metadata:
  labels:
    app: myd
  name: myd
  namespace: default
spec:
  ports:
  - nodePort: 30001
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: myd
  type: NodePort
status:
  loadBalancer: {}

